### ISSUE TITLE
Excalibur 0.17

### ISSUE THREAD

**Issue by Morb0** [excaliburjs/template-electron#7]
On excalibur 0.17 version get error:
`Uncaught SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Developing\ExcaliburJS\RunAndJump\game\index.js:3:10)`

**Comment by eonarheim** [comment]
Updated to the latest excalibur now, sorry for the long delay!
